export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const CHANGE_SCREEN = 'CHANGE_SCREEN'
export const FETCH_TODOS = 'FETCH_TODOS'  // экшн для загрузки todo с сервера
export const SHOW_LOADER = 'SHOW_LOADER'  // индикатор загрузки данных
export const HIDE_LOADER = 'HIDE_LOADER'  // скрытие loader'а
export const SHOW_ERROR = 'SHOW_ERROR'    // показывает ошибки
export const CLEAR_ERROR = 'CLEAR_ERROR'  // очищает ошибки
